//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Game')
export class GameEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  gameName: string;

  @Column('text', { nullable: true })
  gameType: string;

  @Column('text', { nullable: true })
  rulesDescription: string;

  @Column('integer', { nullable: true })
  numberOfPlayers: number;

  @Column('text', { nullable: true })
  difficultyLevel: string;
}
